[package]
name = "wepo-zk"
version = "0.1.0"
edition = "2021"

[dependencies]
winterfell = "0.13.1"
sha3 = "0.10"
serde_json = "1"

[profile.release]
opt-level = 3

[[bin]]
name = "phase1_spike"
path = "src/main.rs"

[[bin]]
name = "phase2_native"
path = "src/bin/phase2_native.rs"

[[bin]]
name = "phase2_merkle"
path = "src/bin/phase2_merkle.rs"

[[bin]]
name = "hashcli"
path = "src/bin/hashcli.rs"

[[bin]]
name = "rescue_len_probe"
path = "src/bin/rescue_len_probe.rs"

[[bin]]
name = "phase2_scaling"
path = "src/bin/phase2_scaling.rs"


[[bin]]
name = "vectors"
path = "src/bin/vectors.rs"

[[bin]]
name = "dump_rescue_constants"
path = "src/bin/dump_rescue_constants.rs"

[[bin]]
name = "poolhash"
path = "src/bin/poolhash.rs"

[[bin]]
name = "phase3_jive"
path = "src/bin/phase3_jive.rs"
